# Base Image
FROM node:22-alpine

# Working Directory
WORKDIR /app

# Copy package files
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy frontend source code
COPY frontend/ .

# Expose Vite port
EXPOSE 5173

# Start Vite Development Server
CMD ["npm", "run", "dev", "--", "--host"]